name: Enforce Commit Style

on: [push]

jobs:
  style_job_local:
    runs-on: ubuntu-latest
    name: Enforce Commit Style

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check style
      uses: ./
      id: test
