name: Enforce Commit Style Release

on: [push]

jobs:
  style_job:
    runs-on: ubuntu-latest
    name: Enforce Commit Style Release

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check style
      uses: telday/enforce-commit-style@v1
      id: test
